apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "confero.fullname" . }}-config
  labels:
    {{- include "confero.labels" . | nindent 4 }}
data:
  CONFERO_HTTP_ADDR: ":8080"
  CONFERO_OIDC_ISSUER_URL: {{ .Values.oidc.issuerURL | quote }}
  CONFERO_OIDC_CLIENT_ID: {{ .Values.oidc.clientID | quote }}
  CONFERO_OIDC_MEMBER_VALUE: {{ .Values.oidc.memberValue | quote }}
  CONFERO_OIDC_ADMIN_VALUE: {{ .Values.oidc.adminValue | quote }}
  CONFERO_PUBLIC_BASE_URL: {{ .Values.publicBaseURL | quote }}
  {{- if .Values.smtp.addr }}
  CONFERO_SMTP_ADDR: {{ .Values.smtp.addr | quote }}
  {{- end }}
  {{- if .Values.smtp.from }}
  CONFERO_SMTP_FROM: {{ .Values.smtp.from | quote }}
  {{- end }}
