apiVersion: v1
kind: Secret
metadata:
  name: {{ include "confero.fullname" . }}-derived
  labels:
    {{- include "confero.labels" . | nindent 4 }}
type: Opaque
data:
  CONFERO_OIDC_REDIRECT_URL: {{ printf "https://%s/auth/callback" .Values.ingress.host | b64enc | quote }}
