// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthStatus = {
    status: 'ok';
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];
