// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type HealthStatus = {
    status: 'ok';
};

export type CurrentUser = {
    id: string;
    email: string;
    name: string;
    roles: Array<'member' | 'admin'>;
};

export type ProblemDetail = {
    title?: string;
    status?: number;
    detail?: string;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: HealthStatus;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/me';
};

export type GetMeErrors = {
    /**
     * Authentication required or token invalid/expired
     */
    401: ProblemDetail;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * Current authenticated user
     */
    200: CurrentUser;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];
