// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEntry = `-- name: InsertAuditEntry :exec
INSERT INTO audit_log (actor_user_id, actor_display_name, actor_oidc_subject, action, entity_type, entity_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAuditEntryParams struct {
	ActorUserID      pgtype.UUID `json:"actor_user_id"`
	ActorDisplayName string      `json:"actor_display_name"`
	ActorOidcSubject string      `json:"actor_oidc_subject"`
	Action           string      `json:"action"`
	EntityType       string      `json:"entity_type"`
	EntityID         uuid.UUID   `json:"entity_id"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) error {
	_, err := q.db.Exec(ctx, insertAuditEntry,
		arg.ActorUserID,
		arg.ActorDisplayName,
		arg.ActorOidcSubject,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, actor_display_name, actor_oidc_subject, action, entity_type, entity_id, created_at
FROM audit_log
WHERE ($1::text IS NULL OR entity_type = $1::text)
  AND ($2::uuid IS NULL OR entity_id = $2::uuid)
  AND ($3::text IS NULL OR actor_oidc_subject = $3::text)
  AND ($4::timestamptz IS NULL OR created_at < $4::timestamptz)
ORDER BY created_at DESC
LIMIT $5::int
`

type ListAuditLogParams struct {
	EntityType       *string            `json:"entity_type"`
	EntityID         pgtype.UUID        `json:"entity_id"`
	ActorOidcSubject *string            `json:"actor_oidc_subject"`
	Before           pgtype.Timestamptz `json:"before"`
	LimitVal         *int32             `json:"limit_val"`
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.EntityType,
		arg.EntityID,
		arg.ActorOidcSubject,
		arg.Before,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.ActorOidcSubject,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
