// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendar.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createCalendarToken = `-- name: CreateCalendarToken :one
INSERT INTO user_calendar_tokens (user_id, token, kind)
VALUES ($1, $2, $3)
RETURNING id, user_id, token, kind, last_used_at, revoked_at, created_at
`

type CreateCalendarTokenParams struct {
	UserID uuid.UUID `json:"user_id"`
	Token  string    `json:"token"`
	Kind   string    `json:"kind"`
}

func (q *Queries) CreateCalendarToken(ctx context.Context, arg CreateCalendarTokenParams) (UserCalendarToken, error) {
	row := q.db.QueryRow(ctx, createCalendarToken, arg.UserID, arg.Token, arg.Kind)
	var i UserCalendarToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Kind,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCalendarTokenByValue = `-- name: GetCalendarTokenByValue :one
UPDATE user_calendar_tokens
SET last_used_at = now()
WHERE token = $1 AND revoked_at IS NULL
RETURNING id, user_id, token, kind, last_used_at, revoked_at, created_at
`

func (q *Queries) GetCalendarTokenByValue(ctx context.Context, token string) (UserCalendarToken, error) {
	row := q.db.QueryRow(ctx, getCalendarTokenByValue, token)
	var i UserCalendarToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.Kind,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCalendarTokensByUser = `-- name: ListCalendarTokensByUser :many
SELECT id, user_id, token, kind, last_used_at, revoked_at, created_at
FROM user_calendar_tokens
WHERE user_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListCalendarTokensByUser(ctx context.Context, userID uuid.UUID) ([]UserCalendarToken, error) {
	rows, err := q.db.Query(ctx, listCalendarTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserCalendarToken
	for rows.Next() {
		var i UserCalendarToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.Kind,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeCalendarTokensByUser = `-- name: RevokeCalendarTokensByUser :exec
UPDATE user_calendar_tokens
SET revoked_at = now()
WHERE user_id = $1 AND kind = $2 AND revoked_at IS NULL
`

type RevokeCalendarTokensByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
}

func (q *Queries) RevokeCalendarTokensByUser(ctx context.Context, arg RevokeCalendarTokensByUserParams) error {
	_, err := q.db.Exec(ctx, revokeCalendarTokensByUser, arg.UserID, arg.Kind)
	return err
}
