// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conferences.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConference = `-- name: CreateConference :one
INSERT INTO conferences (
    name, acronym, year, location, website_url, cfp_url,
    primary_deadline, abstract_deadline, notification_date, camera_ready_date,
    event_start_date, event_end_date, core_rank, h5_index, acceptance_rate_pct,
    dblp_key, notes, created_by, updated_by
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $18
)
RETURNING id, name, acronym, year, location, website_url, cfp_url,
          primary_deadline, abstract_deadline, notification_date, camera_ready_date,
          event_start_date, event_end_date, core_rank, h5_index, acceptance_rate_pct,
          dblp_key, notes, archived_at, created_by, updated_by, created_at, updated_at
`

type CreateConferenceParams struct {
	Name              string             `json:"name"`
	Acronym           string             `json:"acronym"`
	Year              int32              `json:"year"`
	Location          string             `json:"location"`
	WebsiteUrl        *string            `json:"website_url"`
	CfpUrl            *string            `json:"cfp_url"`
	PrimaryDeadline   pgtype.Timestamptz `json:"primary_deadline"`
	AbstractDeadline  pgtype.Timestamptz `json:"abstract_deadline"`
	NotificationDate  pgtype.Timestamptz `json:"notification_date"`
	CameraReadyDate   pgtype.Timestamptz `json:"camera_ready_date"`
	EventStartDate    pgtype.Date        `json:"event_start_date"`
	EventEndDate      pgtype.Date        `json:"event_end_date"`
	CoreRank          *string            `json:"core_rank"`
	H5Index           *int32             `json:"h5_index"`
	AcceptanceRatePct pgtype.Numeric     `json:"acceptance_rate_pct"`
	DblpKey           *string            `json:"dblp_key"`
	Notes             *string            `json:"notes"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateConference(ctx context.Context, arg CreateConferenceParams) (Conference, error) {
	row := q.db.QueryRow(ctx, createConference,
		arg.Name,
		arg.Acronym,
		arg.Year,
		arg.Location,
		arg.WebsiteUrl,
		arg.CfpUrl,
		arg.PrimaryDeadline,
		arg.AbstractDeadline,
		arg.NotificationDate,
		arg.CameraReadyDate,
		arg.EventStartDate,
		arg.EventEndDate,
		arg.CoreRank,
		arg.H5Index,
		arg.AcceptanceRatePct,
		arg.DblpKey,
		arg.Notes,
		arg.CreatedBy,
	)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Year,
		&i.Location,
		&i.WebsiteUrl,
		&i.CfpUrl,
		&i.PrimaryDeadline,
		&i.AbstractDeadline,
		&i.NotificationDate,
		&i.CameraReadyDate,
		&i.EventStartDate,
		&i.EventEndDate,
		&i.CoreRank,
		&i.H5Index,
		&i.AcceptanceRatePct,
		&i.DblpKey,
		&i.Notes,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConference = `-- name: GetConference :one
SELECT id, name, acronym, year, location, website_url, cfp_url,
       primary_deadline, abstract_deadline, notification_date, camera_ready_date,
       event_start_date, event_end_date, core_rank, h5_index, acceptance_rate_pct,
       dblp_key, notes, archived_at, created_by, updated_by, created_at, updated_at
FROM conferences
WHERE id = $1
`

func (q *Queries) GetConference(ctx context.Context, id uuid.UUID) (Conference, error) {
	row := q.db.QueryRow(ctx, getConference, id)
	var i Conference
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Acronym,
		&i.Year,
		&i.Location,
		&i.WebsiteUrl,
		&i.CfpUrl,
		&i.PrimaryDeadline,
		&i.AbstractDeadline,
		&i.NotificationDate,
		&i.CameraReadyDate,
		&i.EventStartDate,
		&i.EventEndDate,
		&i.CoreRank,
		&i.H5Index,
		&i.AcceptanceRatePct,
		&i.DblpKey,
		&i.Notes,
		&i.ArchivedAt,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConferences = `-- name: ListConferences :many
SELECT id, name, acronym, year, location, website_url, cfp_url,
       primary_deadline, abstract_deadline, notification_date, camera_ready_date,
       event_start_date, event_end_date, core_rank, h5_index, acceptance_rate_pct,
       dblp_key, notes, archived_at, created_by, updated_by, created_at, updated_at
FROM conferences
WHERE archived_at IS NULL
ORDER BY primary_deadline ASC NULLS LAST, name ASC
`

func (q *Queries) ListConferences(ctx context.Context) ([]Conference, error) {
	rows, err := q.db.Query(ctx, listConferences)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conference
	for rows.Next() {
		var i Conference
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Year,
			&i.Location,
			&i.WebsiteUrl,
			&i.CfpUrl,
			&i.PrimaryDeadline,
			&i.AbstractDeadline,
			&i.NotificationDate,
			&i.CameraReadyDate,
			&i.EventStartDate,
			&i.EventEndDate,
			&i.CoreRank,
			&i.H5Index,
			&i.AcceptanceRatePct,
			&i.DblpKey,
			&i.Notes,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
