// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID               uuid.UUID          `json:"id"`
	ActorUserID      pgtype.UUID        `json:"actor_user_id"`
	ActorDisplayName string             `json:"actor_display_name"`
	ActorOidcSubject string             `json:"actor_oidc_subject"`
	Action           string             `json:"action"`
	EntityType       string             `json:"entity_type"`
	EntityID         uuid.UUID          `json:"entity_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Conference struct {
	ID                uuid.UUID          `json:"id"`
	Name              string             `json:"name"`
	Acronym           string             `json:"acronym"`
	Year              int32              `json:"year"`
	Location          string             `json:"location"`
	WebsiteUrl        *string            `json:"website_url"`
	CfpUrl            *string            `json:"cfp_url"`
	PrimaryDeadline   pgtype.Timestamptz `json:"primary_deadline"`
	AbstractDeadline  pgtype.Timestamptz `json:"abstract_deadline"`
	NotificationDate  pgtype.Timestamptz `json:"notification_date"`
	CameraReadyDate   pgtype.Timestamptz `json:"camera_ready_date"`
	EventStartDate    pgtype.Date        `json:"event_start_date"`
	EventEndDate      pgtype.Date        `json:"event_end_date"`
	CoreRank          *string            `json:"core_rank"`
	H5Index           *int32             `json:"h5_index"`
	AcceptanceRatePct pgtype.Numeric     `json:"acceptance_rate_pct"`
	DblpKey           *string            `json:"dblp_key"`
	Notes             *string            `json:"notes"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ConferenceTag struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	TagID        uuid.UUID `json:"tag_id"`
}

type ConferenceTrack struct {
	ConferenceID uuid.UUID `json:"conference_id"`
	TrackCode    string    `json:"track_code"`
}

type DigestDispatchLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	WeekStarting pgtype.Date        `json:"week_starting"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Status       string             `json:"status"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	Attempts     int32              `json:"attempts"`
	LastError    *string            `json:"last_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type ReminderDispatchLog struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ConferenceID uuid.UUID          `json:"conference_id"`
	DeadlineKind string             `json:"deadline_kind"`
	LeadTimeDays int32              `json:"lead_time_days"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Status       string             `json:"status"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	Attempts     int32              `json:"attempts"`
	LastError    *string            `json:"last_error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Star struct {
	UserID       uuid.UUID          `json:"user_id"`
	ConferenceID uuid.UUID          `json:"conference_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Tag struct {
	ID        uuid.UUID          `json:"id"`
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Track struct {
	Code        string             `json:"code"`
	DisplayName string             `json:"display_name"`
	SortOrder   int32              `json:"sort_order"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	OidcIssuer  string             `json:"oidc_issuer"`
	OidcSubject string             `json:"oidc_subject"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserCalendarToken struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Token      string             `json:"token"`
	Kind       string             `json:"kind"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UserSetting struct {
	UserID                   uuid.UUID          `json:"user_id"`
	Timezone                 string             `json:"timezone"`
	ReminderLeadDays         []int32            `json:"reminder_lead_days"`
	WeeklyDigestEnabled      bool               `json:"weekly_digest_enabled"`
	WeeklyDigestDay          int16              `json:"weekly_digest_day"`
	WeeklyDigestHour         int16              `json:"weekly_digest_hour"`
	WeeklyDigestHorizonWeeks int16              `json:"weekly_digest_horizon_weeks"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}
