// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reminders.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelConferenceReminders = `-- name: CancelConferenceReminders :exec
UPDATE reminder_dispatch_log
SET status     = 'cancelled',
    updated_at = now()
WHERE status = 'pending'
  AND conference_id = $1
`

// Used when archiving: keeps history of planned-but-cancelled reminders.
func (q *Queries) CancelConferenceReminders(ctx context.Context, conferenceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelConferenceReminders, conferenceID)
	return err
}

const cancelUserConferenceReminders = `-- name: CancelUserConferenceReminders :exec
UPDATE reminder_dispatch_log
SET status     = 'cancelled',
    updated_at = now()
WHERE status = 'pending'
  AND user_id       = $1
  AND conference_id = $2
`

type CancelUserConferenceRemindersParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

// Used when unstarring: preserves history, prevents re-send of the same lead_time.
func (q *Queries) CancelUserConferenceReminders(ctx context.Context, arg CancelUserConferenceRemindersParams) error {
	_, err := q.db.Exec(ctx, cancelUserConferenceReminders, arg.UserID, arg.ConferenceID)
	return err
}

const countPendingRemindersForUser = `-- name: CountPendingRemindersForUser :one
SELECT COUNT(*) FROM reminder_dispatch_log
WHERE user_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingRemindersForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingRemindersForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReminderRows = `-- name: CountReminderRows :one
SELECT COUNT(*) FROM reminder_dispatch_log
WHERE user_id = $1 AND conference_id = $2
`

type CountReminderRowsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

func (q *Queries) CountReminderRows(ctx context.Context, arg CountReminderRowsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReminderRows, arg.UserID, arg.ConferenceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConferencePendingReminders = `-- name: DeleteConferencePendingReminders :exec
DELETE FROM reminder_dispatch_log
WHERE status = 'pending'
  AND conference_id = $1
`

// Used when re-materializing after a deadline change: deletes so fresh rows can be inserted.
func (q *Queries) DeleteConferencePendingReminders(ctx context.Context, conferenceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteConferencePendingReminders, conferenceID)
	return err
}

const deleteUserConferencePendingReminders = `-- name: DeleteUserConferencePendingReminders :exec
DELETE FROM reminder_dispatch_log
WHERE status = 'pending'
  AND user_id       = $1
  AND conference_id = $2
`

type DeleteUserConferencePendingRemindersParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

// Used when re-materializing a single (user, conference) pair after settings change.
func (q *Queries) DeleteUserConferencePendingReminders(ctx context.Context, arg DeleteUserConferencePendingRemindersParams) error {
	_, err := q.db.Exec(ctx, deleteUserConferencePendingReminders, arg.UserID, arg.ConferenceID)
	return err
}

const insertReminderRow = `-- name: InsertReminderRow :exec
INSERT INTO reminder_dispatch_log
    (user_id, conference_id, deadline_kind, lead_time_days, scheduled_for)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, conference_id, deadline_kind, lead_time_days) DO NOTHING
`

type InsertReminderRowParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	ConferenceID uuid.UUID          `json:"conference_id"`
	DeadlineKind string             `json:"deadline_kind"`
	LeadTimeDays int32              `json:"lead_time_days"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
}

func (q *Queries) InsertReminderRow(ctx context.Context, arg InsertReminderRowParams) error {
	_, err := q.db.Exec(ctx, insertReminderRow,
		arg.UserID,
		arg.ConferenceID,
		arg.DeadlineKind,
		arg.LeadTimeDays,
		arg.ScheduledFor,
	)
	return err
}
