// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduler.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingReminders = `-- name: CountPendingReminders :one
SELECT COUNT(*) FROM reminder_dispatch_log WHERE status = 'pending'
`

func (q *Queries) CountPendingReminders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReminders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementReminderAttempt = `-- name: IncrementReminderAttempt :exec
UPDATE reminder_dispatch_log
SET attempts   = attempts + 1,
    last_error = $1,
    updated_at = now()
WHERE id = $2
`

type IncrementReminderAttemptParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) IncrementReminderAttempt(ctx context.Context, arg IncrementReminderAttemptParams) error {
	_, err := q.db.Exec(ctx, incrementReminderAttempt, arg.LastError, arg.ID)
	return err
}

const markReminderFailed = `-- name: MarkReminderFailed :exec
UPDATE reminder_dispatch_log
SET status     = 'failed',
    last_error = $1,
    updated_at = now()
WHERE id = $2
`

type MarkReminderFailedParams struct {
	LastError *string   `json:"last_error"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) MarkReminderFailed(ctx context.Context, arg MarkReminderFailedParams) error {
	_, err := q.db.Exec(ctx, markReminderFailed, arg.LastError, arg.ID)
	return err
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE reminder_dispatch_log
SET status     = 'sent',
    sent_at    = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}

const selectDueReminders = `-- name: SelectDueReminders :many
SELECT r.id,
       r.user_id,
       r.conference_id,
       r.deadline_kind,
       r.lead_time_days,
       r.scheduled_for,
       r.attempts,
       u.email        AS user_email,
       u.display_name AS user_name,
       c.name         AS conference_name,
       c.acronym      AS conference_acronym
FROM reminder_dispatch_log r
JOIN users       u ON u.id = r.user_id
JOIN conferences c ON c.id = r.conference_id
WHERE r.status = 'pending'
  AND r.scheduled_for <= $1
ORDER BY r.scheduled_for
LIMIT 50
FOR UPDATE OF r SKIP LOCKED
`

type SelectDueRemindersRow struct {
	ID                uuid.UUID          `json:"id"`
	UserID            uuid.UUID          `json:"user_id"`
	ConferenceID      uuid.UUID          `json:"conference_id"`
	DeadlineKind      string             `json:"deadline_kind"`
	LeadTimeDays      int32              `json:"lead_time_days"`
	ScheduledFor      pgtype.Timestamptz `json:"scheduled_for"`
	Attempts          int32              `json:"attempts"`
	UserEmail         string             `json:"user_email"`
	UserName          string             `json:"user_name"`
	ConferenceName    string             `json:"conference_name"`
	ConferenceAcronym string             `json:"conference_acronym"`
}

func (q *Queries) SelectDueReminders(ctx context.Context, now pgtype.Timestamptz) ([]SelectDueRemindersRow, error) {
	rows, err := q.db.Query(ctx, selectDueReminders, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectDueRemindersRow
	for rows.Next() {
		var i SelectDueRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ConferenceID,
			&i.DeadlineKind,
			&i.LeadTimeDays,
			&i.ScheduledFor,
			&i.Attempts,
			&i.UserEmail,
			&i.UserName,
			&i.ConferenceName,
			&i.ConferenceAcronym,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectExpiredConferences = `-- name: SelectExpiredConferences :many
SELECT id FROM conferences
WHERE archived_at IS NULL
  AND event_end_date IS NOT NULL
  AND event_end_date < (CURRENT_DATE - $1::int)
FOR UPDATE SKIP LOCKED
`

func (q *Queries) SelectExpiredConferences(ctx context.Context, graceDays int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, selectExpiredConferences, graceDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
