// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT user_id, timezone, reminder_lead_days,
       weekly_digest_enabled, weekly_digest_day, weekly_digest_hour,
       weekly_digest_horizon_weeks, updated_at
FROM user_settings
WHERE user_id = $1
`

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (UserSetting, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.ReminderLeadDays,
		&i.WeeklyDigestEnabled,
		&i.WeeklyDigestDay,
		&i.WeeklyDigestHour,
		&i.WeeklyDigestHorizonWeeks,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserSettings = `-- name: UpdateUserSettings :one
UPDATE user_settings
SET timezone                    = $1,
    reminder_lead_days          = $2,
    weekly_digest_enabled       = $3,
    weekly_digest_day           = $4,
    weekly_digest_hour          = $5,
    weekly_digest_horizon_weeks = $6,
    updated_at                  = now()
WHERE user_id = $7
RETURNING user_id, timezone, reminder_lead_days,
          weekly_digest_enabled, weekly_digest_day, weekly_digest_hour,
          weekly_digest_horizon_weeks, updated_at
`

type UpdateUserSettingsParams struct {
	Timezone                 string    `json:"timezone"`
	ReminderLeadDays         []int32   `json:"reminder_lead_days"`
	WeeklyDigestEnabled      bool      `json:"weekly_digest_enabled"`
	WeeklyDigestDay          int16     `json:"weekly_digest_day"`
	WeeklyDigestHour         int16     `json:"weekly_digest_hour"`
	WeeklyDigestHorizonWeeks int16     `json:"weekly_digest_horizon_weeks"`
	UserID                   uuid.UUID `json:"user_id"`
}

func (q *Queries) UpdateUserSettings(ctx context.Context, arg UpdateUserSettingsParams) (UserSetting, error) {
	row := q.db.QueryRow(ctx, updateUserSettings,
		arg.Timezone,
		arg.ReminderLeadDays,
		arg.WeeklyDigestEnabled,
		arg.WeeklyDigestDay,
		arg.WeeklyDigestHour,
		arg.WeeklyDigestHorizonWeeks,
		arg.UserID,
	)
	var i UserSetting
	err := row.Scan(
		&i.UserID,
		&i.Timezone,
		&i.ReminderLeadDays,
		&i.WeeklyDigestEnabled,
		&i.WeeklyDigestDay,
		&i.WeeklyDigestHour,
		&i.WeeklyDigestHorizonWeeks,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id)
VALUES ($1)
ON CONFLICT (user_id) DO NOTHING
`

func (q *Queries) UpsertUserSettings(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, upsertUserSettings, userID)
	return err
}
