// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stars.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createStar = `-- name: CreateStar :exec
INSERT INTO stars (user_id, conference_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateStarParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

func (q *Queries) CreateStar(ctx context.Context, arg CreateStarParams) error {
	_, err := q.db.Exec(ctx, createStar, arg.UserID, arg.ConferenceID)
	return err
}

const deleteStar = `-- name: DeleteStar :execrows
DELETE FROM stars
WHERE user_id = $1 AND conference_id = $2
`

type DeleteStarParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

func (q *Queries) DeleteStar(ctx context.Context, arg DeleteStarParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStar, arg.UserID, arg.ConferenceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStar = `-- name: GetStar :one
SELECT user_id, conference_id, created_at
FROM stars
WHERE user_id = $1 AND conference_id = $2
`

type GetStarParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ConferenceID uuid.UUID `json:"conference_id"`
}

func (q *Queries) GetStar(ctx context.Context, arg GetStarParams) (Star, error) {
	row := q.db.QueryRow(ctx, getStar, arg.UserID, arg.ConferenceID)
	var i Star
	err := row.Scan(&i.UserID, &i.ConferenceID, &i.CreatedAt)
	return i, err
}

const listUserStarredConferences = `-- name: ListUserStarredConferences :many
SELECT c.id, c.name, c.acronym, c.year, c.location, c.website_url, c.cfp_url, c.primary_deadline, c.abstract_deadline, c.notification_date, c.camera_ready_date, c.event_start_date, c.event_end_date, c.core_rank, c.h5_index, c.acceptance_rate_pct, c.dblp_key, c.notes, c.archived_at, c.created_by, c.updated_by, c.created_at, c.updated_at
FROM conferences c
INNER JOIN stars s ON s.conference_id = c.id
WHERE s.user_id = $1
ORDER BY c.primary_deadline ASC NULLS LAST, c.name ASC
`

func (q *Queries) ListUserStarredConferences(ctx context.Context, userID uuid.UUID) ([]Conference, error) {
	rows, err := q.db.Query(ctx, listUserStarredConferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Conference
	for rows.Next() {
		var i Conference
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Acronym,
			&i.Year,
			&i.Location,
			&i.WebsiteUrl,
			&i.CfpUrl,
			&i.PrimaryDeadline,
			&i.AbstractDeadline,
			&i.NotificationDate,
			&i.CameraReadyDate,
			&i.EventStartDate,
			&i.EventEndDate,
			&i.CoreRank,
			&i.H5Index,
			&i.AcceptanceRatePct,
			&i.DblpKey,
			&i.Notes,
			&i.ArchivedAt,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersStarringConferenceWithSettings = `-- name: ListUsersStarringConferenceWithSettings :many
SELECT s.user_id, us.reminder_lead_days, us.timezone
FROM stars s
JOIN user_settings us ON us.user_id = s.user_id
WHERE s.conference_id = $1
`

type ListUsersStarringConferenceWithSettingsRow struct {
	UserID           uuid.UUID `json:"user_id"`
	ReminderLeadDays []int32   `json:"reminder_lead_days"`
	Timezone         string    `json:"timezone"`
}

func (q *Queries) ListUsersStarringConferenceWithSettings(ctx context.Context, conferenceID uuid.UUID) ([]ListUsersStarringConferenceWithSettingsRow, error) {
	rows, err := q.db.Query(ctx, listUsersStarringConferenceWithSettings, conferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersStarringConferenceWithSettingsRow
	for rows.Next() {
		var i ListUsersStarringConferenceWithSettingsRow
		if err := rows.Scan(&i.UserID, &i.ReminderLeadDays, &i.Timezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
