// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getTagBySlug = `-- name: GetTagBySlug :one
SELECT id, slug, name FROM tags WHERE slug = $1
`

type GetTagBySlugRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) GetTagBySlug(ctx context.Context, slug string) (GetTagBySlugRow, error) {
	row := q.db.QueryRow(ctx, getTagBySlug, slug)
	var i GetTagBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, slug, name FROM tags ORDER BY slug
`

type ListTagsRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) ListTags(ctx context.Context) ([]ListTagsRow, error) {
	rows, err := q.db.Query(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTagsRow
	for rows.Next() {
		var i ListTagsRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTagBySlug = `-- name: UpsertTagBySlug :one
INSERT INTO tags (slug, name)
VALUES ($1, $2)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name
RETURNING id, slug, name
`

type UpsertTagBySlugParams struct {
	Slug string `json:"slug"`
	Name string `json:"name"`
}

type UpsertTagBySlugRow struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
}

func (q *Queries) UpsertTagBySlug(ctx context.Context, arg UpsertTagBySlugParams) (UpsertTagBySlugRow, error) {
	row := q.db.QueryRow(ctx, upsertTagBySlug, arg.Slug, arg.Name)
	var i UpsertTagBySlugRow
	err := row.Scan(&i.ID, &i.Slug, &i.Name)
	return i, err
}
