// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tracks.sql

package repository

import (
	"context"
)

const listTracks = `-- name: ListTracks :many
SELECT code, display_name, sort_order FROM tracks ORDER BY sort_order, code
`

type ListTracksRow struct {
	Code        string `json:"code"`
	DisplayName string `json:"display_name"`
	SortOrder   int32  `json:"sort_order"`
}

func (q *Queries) ListTracks(ctx context.Context) ([]ListTracksRow, error) {
	rows, err := q.db.Query(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(&i.Code, &i.DisplayName, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
