// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, oidc_issuer, oidc_subject, email, display_name, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (oidc_issuer, oidc_subject, email, display_name, last_login_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (oidc_issuer, oidc_subject) DO UPDATE
    SET email         = EXCLUDED.email,
        display_name  = EXCLUDED.display_name,
        last_login_at = now()
RETURNING id, oidc_issuer, oidc_subject, email, display_name, last_login_at, created_at, updated_at
`

type UpsertUserParams struct {
	OidcIssuer  string `json:"oidc_issuer"`
	OidcSubject string `json:"oidc_subject"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.OidcIssuer,
		arg.OidcSubject,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OidcIssuer,
		&i.OidcSubject,
		&i.Email,
		&i.DisplayName,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
